version: '2.2'
services:
  mongodb:
    restart: always
    build: mongodb
    image: zucchinidev/mongodb
    container_name: mongodb_golang
    volumes:
    - /var/lib/mongodb:/data/db
    ports:
    - "27017:27017"
    networks:
      golang:
        aliases:
        - mongodb
    command: "--storageEngine wiredTiger"
    logging:
      options:
        tag: "{{.DaemonName}}/mongodb"

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
    - "4160:4160" # connect with nsqd
    - "4161:4161" # connect with nsqadmin
    networks:
      golang:
        aliases:
        - nsqlookupd

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=172.23.0.199
    depends_on:
    - nsqlookupd
    ports:
    - "4150:4150"
    - "4151:4151"
    networks:
      golang:
        ipv4_address: 172.23.0.199
        aliases:
        - nsqd

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
    - nsqlookupd
    ports:
    - "4171:4171"
    networks:
      golang:
        aliases:
        - nsqadmin

  counter:
    extends:
      file: docker-compose-common.yml
      service: common_service
    build:
      context: ./counter
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./counter:/go/src/github.com/zucchinidev/building-distributed-system-golang/counter
    depends_on:
    - nsqlookupd
    networks:
      golang:
        aliases:
        - counter

  twittervotes:
    extends:
      file: docker-compose-common.yml
      service: common_service
    build:
      context: ./twittervotes
      args:
        app_env: ${APP_ENV}
    volumes:
    - ./twittervotes:/go/src/github.com/zucchinidev/building-distributed-system-golang/twittervotes
    depends_on:
    - nsqd
    networks:
      golang:
        aliases:
        - twittervotes

  api:
    extends:
      file: docker-compose-common.yml
      service: common_service
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
    - ./api:/go/src/github.com/zucchinidev/building-distributed-system-golang/api
    ports:
      - "8080:8080"
    depends_on:
    - mongodb
    networks:
      golang:
        aliases:
        - api
  web:
    extends:
      file: docker-compose-common.yml
      service: common_service
    build:
      context: ./web
      args:
        app_env: ${APP_ENV}
    volumes:
    - ./web:/go/src/github.com/zucchinidev/building-distributed-system-golang/web
    ports:
      - "8081:8081"
    networks:
      golang:
        aliases:
        - web


networks:
  golang:
    external: true
